import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "@mui/material";
import Header from "@/components/Header";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Natural Cat Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ua">
      <body className={inter.className}>
        <Providers>
          <Container maxWidth="sm">
            <Header />
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
